// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using sistemaAdministracion.Data;

#nullable disable

namespace sistemaAdministracion.Migrations
{
    [DbContext(typeof(sistemaAdministracionContext))]
    partial class sistemaAdministracionContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CandidaturaPapeleta", b =>
                {
                    b.Property<int>("CandidatosId")
                        .HasColumnType("int");

                    b.Property<int>("PapeletaId")
                        .HasColumnType("int");

                    b.HasKey("CandidatosId", "PapeletaId");

                    b.HasIndex("PapeletaId");

                    b.ToTable("CandidaturaPapeleta");
                });

            modelBuilder.Entity("sistemaAdministracion.Models.Candidatura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CargoId")
                        .HasColumnType("int");

                    b.Property<string>("NombreCandidato")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PartidoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CargoId");

                    b.HasIndex("PartidoId");

                    b.ToTable("Candidaturas");
                });

            modelBuilder.Entity("sistemaAdministracion.Models.Cargo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Cargos");
                });

            modelBuilder.Entity("sistemaAdministracion.Models.CargoSeccion", b =>
                {
                    b.Property<int>("CargoId")
                        .HasColumnType("int");

                    b.Property<int>("SeccionId")
                        .HasColumnType("int");

                    b.HasKey("CargoId", "SeccionId");

                    b.HasIndex("SeccionId");

                    b.ToTable("CargoSecciones");
                });

            modelBuilder.Entity("sistemaAdministracion.Models.Eleccion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Elecciones");
                });

            modelBuilder.Entity("sistemaAdministracion.Models.Jurado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MesaElectoralId")
                        .HasColumnType("int");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MesaElectoralId");

                    b.ToTable("Jurados");
                });

            modelBuilder.Entity("sistemaAdministracion.Models.MesaElectoral", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.Property<int>("RecintoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RecintoId");

                    b.ToTable("MesasElectorales");
                });

            modelBuilder.Entity("sistemaAdministracion.Models.Papeleta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EleccionId")
                        .HasColumnType("int");

                    b.Property<int>("SeccionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EleccionId");

                    b.HasIndex("SeccionId");

                    b.ToTable("Papeletas");
                });

            modelBuilder.Entity("sistemaAdministracion.Models.Partido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sigla")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Partidos");
                });

            modelBuilder.Entity("sistemaAdministracion.Models.Recinto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Coordenadas")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Recintos");
                });

            modelBuilder.Entity("sistemaAdministracion.Models.Seccion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Coordenadas")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Secciones");
                });

            modelBuilder.Entity("sistemaAdministracion.Models.SeccionEleccion", b =>
                {
                    b.Property<int>("EleccionId")
                        .HasColumnType("int");

                    b.Property<int>("SeccionId")
                        .HasColumnType("int");

                    b.HasKey("EleccionId", "SeccionId");

                    b.HasIndex("SeccionId");

                    b.ToTable("SeccionElecciones");
                });

            modelBuilder.Entity("sistemaAdministracion.Models.Votante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApellidoPaterno")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MesaElectoralId")
                        .HasColumnType("int");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MesaElectoralId");

                    b.ToTable("Votantes");
                });

            modelBuilder.Entity("CandidaturaPapeleta", b =>
                {
                    b.HasOne("sistemaAdministracion.Models.Candidatura", null)
                        .WithMany()
                        .HasForeignKey("CandidatosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("sistemaAdministracion.Models.Papeleta", null)
                        .WithMany()
                        .HasForeignKey("PapeletaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("sistemaAdministracion.Models.Candidatura", b =>
                {
                    b.HasOne("sistemaAdministracion.Models.Cargo", "Cargo")
                        .WithMany()
                        .HasForeignKey("CargoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("sistemaAdministracion.Models.Partido", "Partido")
                        .WithMany("Candidaturas")
                        .HasForeignKey("PartidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cargo");

                    b.Navigation("Partido");
                });

            modelBuilder.Entity("sistemaAdministracion.Models.CargoSeccion", b =>
                {
                    b.HasOne("sistemaAdministracion.Models.Cargo", "Cargo")
                        .WithMany("Secciones")
                        .HasForeignKey("CargoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("sistemaAdministracion.Models.Seccion", "Seccion")
                        .WithMany("Cargos")
                        .HasForeignKey("SeccionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cargo");

                    b.Navigation("Seccion");
                });

            modelBuilder.Entity("sistemaAdministracion.Models.Jurado", b =>
                {
                    b.HasOne("sistemaAdministracion.Models.MesaElectoral", "MesaElectoral")
                        .WithMany("Jurados")
                        .HasForeignKey("MesaElectoralId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MesaElectoral");
                });

            modelBuilder.Entity("sistemaAdministracion.Models.MesaElectoral", b =>
                {
                    b.HasOne("sistemaAdministracion.Models.Recinto", "Recinto")
                        .WithMany("Mesas")
                        .HasForeignKey("RecintoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recinto");
                });

            modelBuilder.Entity("sistemaAdministracion.Models.Papeleta", b =>
                {
                    b.HasOne("sistemaAdministracion.Models.Eleccion", "Eleccion")
                        .WithMany()
                        .HasForeignKey("EleccionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("sistemaAdministracion.Models.Seccion", "Seccion")
                        .WithMany()
                        .HasForeignKey("SeccionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Eleccion");

                    b.Navigation("Seccion");
                });

            modelBuilder.Entity("sistemaAdministracion.Models.SeccionEleccion", b =>
                {
                    b.HasOne("sistemaAdministracion.Models.Eleccion", "Eleccion")
                        .WithMany("SeccionesAfectadas")
                        .HasForeignKey("EleccionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("sistemaAdministracion.Models.Seccion", "Seccion")
                        .WithMany("Elecciones")
                        .HasForeignKey("SeccionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Eleccion");

                    b.Navigation("Seccion");
                });

            modelBuilder.Entity("sistemaAdministracion.Models.Votante", b =>
                {
                    b.HasOne("sistemaAdministracion.Models.MesaElectoral", "MesaElectoral")
                        .WithMany("Votantes")
                        .HasForeignKey("MesaElectoralId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MesaElectoral");
                });

            modelBuilder.Entity("sistemaAdministracion.Models.Cargo", b =>
                {
                    b.Navigation("Secciones");
                });

            modelBuilder.Entity("sistemaAdministracion.Models.Eleccion", b =>
                {
                    b.Navigation("SeccionesAfectadas");
                });

            modelBuilder.Entity("sistemaAdministracion.Models.MesaElectoral", b =>
                {
                    b.Navigation("Jurados");

                    b.Navigation("Votantes");
                });

            modelBuilder.Entity("sistemaAdministracion.Models.Partido", b =>
                {
                    b.Navigation("Candidaturas");
                });

            modelBuilder.Entity("sistemaAdministracion.Models.Recinto", b =>
                {
                    b.Navigation("Mesas");
                });

            modelBuilder.Entity("sistemaAdministracion.Models.Seccion", b =>
                {
                    b.Navigation("Cargos");

                    b.Navigation("Elecciones");
                });
#pragma warning restore 612, 618
        }
    }
}
