# Generated by Django 4.2.23 on 2025-06-23 20:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recinto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Votante',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ci', models.CharField(max_length=20, unique=True)),
                ('nombre_completo', models.CharField(max_length=150)),
                ('direccion', models.TextField()),
                ('foto_anverso', models.ImageField(upload_to='carnets/anverso/')),
                ('foto_reverso', models.ImageField(upload_to='carnets/reverso/')),
                ('foto_rostro', models.ImageField(upload_to='rostros/')),
                ('recinto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='votantes.recinto')),
            ],
        ),
    ]
